language: go

go:
  - 1.8

dist: trusty
sudo: false

install:
  - go get -u github.com/kardianos/govendor
  - go get -u github.com/golang/lint/golint
  - go get -u github.com/kisielk/errcheck
  - go get -u github.com/fzipp/gocyclo
  - go get -u github.com/gordonklaus/ineffassign
  - go get -u github.com/client9/misspell/cmd/misspell
  - go get -u ./...
  - govendor sync

script:
  - make
  - make travis-presubmit
